### ISSUE TITLE
sql语句中使用 string 未能正常插入 

### ISSUE THREAD

**Issue by dnybz** [qicosmos/ormpp#1]
问题现象：当我插入一条记录，sql语句中使用 string  a, b 未能正常插入
测试代码如下：

const char* create_user = "create table if not exists user(id integer PRIMARY KEY AUTOINCREMENT, name text, pwd text,"
		"qq text, sex integer, role integer)";

	dbng db;
	int result = db.create_database("test.db");

	result = db.excecute(create_user);

	const char* insert_user = "insert into user(id, name,pwd,qq,sex,role) values(?,?,?,?,?,?);";

	std::string a = "testa";
	std::string b = "testb";
	result = db.excecute(insert_user, 1, a.c_str(), b.c_str(), "12345", 1, 1);

**Comment by qicosmos** [comment]
已经修复，请验证一下。

**Comment by dnybz** [comment]
测试可以了。
