### ISSUE TITLE
运行MySQL的tests时报错，栈溢出

### ISSUE THREAD

**Issue by bz-2021** [qicosmos/ormpp#101]
![image](https://github.com/qicosmos/ormpp/assets/109196978/44a80e63-67d8-4d03-a091-b31d95ad33b0)
![image](https://github.com/qicosmos/ormpp/assets/109196978/4953e423-2337-4e9c-a6ac-7260f91fa0c7)
运行环境gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
是我自身的问题吗？谢谢

**Comment by qicosmos** [comment]
看起来是代码的问题

**Comment by Jacyking** [comment]
先运行example时 会创建person表有四个字段，在运行tests时 定位到tuple接受select person.*会越界，将example的字段与tests字段保持一致 #102

**Comment by bz-2021** [comment]
> 先运行example时 会创建person表有四个字段，在运行tests时 定位到tuple接受select person.*会越界，将example的字段与tests字段保持一致 #102

## 已解决
