### ISSUE TITLE
sqlite.connect err

### ISSUE THREAD

**Issue by littleboss01** [qicosmos/ormpp#103]
sqlite.hpp

首页例子报错
`sqlite.connect("127.0.0.1", "root", "12345", "testdb");`

`  template <typename... Args>
  bool connect(Args &&...args) {
    auto r = sqlite3_open(std::forward<Args>(args)..., &handle_);`
sqlite3_open不支持5个参数

**Comment by qicosmos** [comment]
更新了readme，sqlite是本地文件，所以用户密码参数是多余的。
sqlite.connect("127.0.0.1", "testdb");
