### ISSUE TITLE
mysql无法query获取std::optional字段

### ISSUE THREAD

**Issue by BisonReto** [qicosmos/ormpp#104]
struct person {
  int id;
  std::optional<std::string> name;
  std::optional<int> age;
};
REFLECTION(person, id, name, age)
![image](https://github.com/qicosmos/ormpp/assets/14340149/23357ec6-8a10-46b4-846a-9782afd51724)
无论是通过auto result = mysql.query("select * from person");还是auto result = mysql.query<person>();查询result大小为0。
去除 std::optional这个就没啥问题，请问能解决上述bug吗？谢谢

**Comment by qicosmos** [comment]
sqlite 是可以的吧，也帮助测试一下。

**Comment by Jacyking** [comment]
mysql已解决，请拉取最新代码

**Comment by BisonReto** [comment]
解决了，非常感谢！

**Comment by lemon19900815** [comment]
在使用最新的master代码运行单元测试，这个问题仍然存在。
![微信截图_20240313141947](https://github.com/qicosmos/ormpp/assets/7922557/6b7be9c2-7a8a-47c1-abad-b6914e5afef9)

**Comment by Jacyking** [comment]
> 在使用最新的master代码运行单元测试，这个问题仍然存在。 ![微信截图_20240313141947](https://private-user-images.githubusercontent.com/7922557/312335053-6b7be9c2-7a8a-47c1-abad-b6914e5afef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTYwMzIsIm5iZiI6MTcxMDMxNTczMiwicGF0aCI6Ii83OTIyNTU3LzMxMjMzNTA1My02YjdiZTljMi03YThhLTQ3YzEtYWJhZC1iNjkxNGU1YWZlZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMDc0MjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIyOWE1NTA5MmMyODllNmZiN2Q2M2I5MzdjNDQ3YzcyZWMyZWUzN2UwYmVhMWJiYTFjYWJmMzU1MzdjMzllYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O-10kOfu5sG0UxbL7sP5MX9PwIH2A9bQf0m8yjIEHkY)

show your code please.

**Comment by lemon19900815** [comment]
请看下面这个测试用例：`auto vec1 = mysql.query<test_optional>();`。
我是在vs2022下，使用mysql5.7和mysql8.0都存在这个问题；
![QQ拼音截图未命名](https://github.com/qicosmos/ormpp/assets/7922557/b1c72b45-0f7e-41c4-ad55-28b2808dd356)

**Comment by Jacyking** [comment]
啊？单元测试都过了啊 可是

**Comment by Jacyking** [comment]
要不，你加qq群吧

**Comment by lemon19900815** [comment]
好的。
