### ISSUE TITLE
blob数据类型怎么存储呢？

### ISSUE THREAD

**Issue by sudo-rm-rf-run** [qicosmos/ormpp#13]
你好，请问blob数据类型怎么存储呢？

**Comment by qicosmos** [comment]
目前还没支持blob，如果需要存储的内容不多可以先用TEXT，我后面支持一下blob。

**Comment by micfan** [comment]
1. 发现 Sqlite 的 integer 字段类型 在 db.create_datatable() 后是 TEXT 类型
1. 看到 struct 中 有标注 `// key` 的注释，但 sqlite 里没有实现该主键

**Comment by qicosmos** [comment]
是所有的integer字段都变成text类型了吗？

**Comment by micfan** [comment]
@qicosmos 是的，Sqlite3 生成的 创建表语句，每个字段都丢失了类型信息
