### ISSUE TITLE
c++20编译报错

### ISSUE THREAD

**Issue by obqrn** [qicosmos/ormpp#148]
c++20编译报错，iguana库报错，std::numeric_limits<std::uint32_t>::max报error C2589: “(”:“::”右边的非法标记，应该是max和min被宏定义了就会出现。

iguana更新到最新应该可以解决。

**Comment by qicosmos** [comment]
确定吗，你能编译一下最新的iguana试一下吗？

**Comment by qicosmos** [comment]
另外你是什么编译器，版本多少？

**Comment by AriJing** [comment]
我也遇到这个问题了。使用的是VS 2022，C++ 20标准

**Comment by obqrn** [comment]
全局define NOMINMAX即可

**Comment by Jacyking** [comment]
> 全局define NOMINMAX即可

可以在cmake里写 define， 还有确定是最新的ormpp吗...
