### ISSUE TITLE
AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY

### ISSUE THREAD

**Issue by runner-ccl** [qicosmos/ormpp#149]
用的example里面的例子，但是将相关的代码集成到自己的项目代码中时，create table的时候报错：AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY

**Comment by Jacyking** [comment]
有code吗？

**Comment by runner-ccl** [comment]
代码在-O0优化状态下，会发生断错误

**Comment by qicosmos** [comment]
有测试代码吗？

**Comment by NinethDimension** [comment]
我碰到了题主一样的报错，原因是把代码从example集成到自己项目中时没有添加add_definitions(-DORMPP_ENABLE_SQLITE3)。没这个宏编译正常就是生成的DDL语句没有类型字段
