### ISSUE TITLE
Sanitizer supported only for debug type

### ISSUE THREAD

**Issue by xfmy** [qicosmos/ormpp#158]
cmake -B build -DENABLE_MYSQL=ON -DCMAKE_BUILD_TYPE=Release
编译release就不可以啊

----------------------
CMake Warning at cmake/develop.cmake:49 (message):
  Sanitizer supported only for debug type
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)

**Comment by Jacyking** [comment]
just warning
