### ISSUE TITLE
ormpp::get_sql_conditions 重定义

### ISSUE THREAD

**Issue by mozeat-sun** [qicosmos/ormpp#17]
如果把dbng.hpp 和sqlite.hpp放在同一个头文件里就会报编译重定义

multiple definition of `ormpp::get_sql_conditions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
obj\Debug\main.o:D:\Code\codeprj\ormpp/../../database/ormpp-master/utility.hpp:192: first defined here

**Comment by qicosmos** [comment]
要加inline

**Comment by qicosmos** [comment]
已修复。
