### ISSUE TITLE
表中的字段不能使用集合映射。

### ISSUE THREAD

**Issue by sc-bai** [qicosmos/ormpp#174]
/*
	表及字段
*/
struct TableAfterSignalData : public TableBaseField {
	std::string key;
    int64_t start_timestamp;
    int32_t period;
	uint32_t length;
    int data;
    //float data[10];// error with error C2665: “ormpp::ormpp_sqlite::type_to_name”:
    //std::vector<float> data; // error with error C2665: “ormpp::ormpp_sqlite::type_to_name”: 
    std::string TableName() {
        return "AfterSignalData";
    }
    void clear() {
        key = "";
        start_timestamp = 0;
        period = 0;
        length = 0;
        // data.clear();
    }
};
REGISTER_AUTO_KEY(TableAfterSignalData, id)
REFLECTION_WITH_NAME(TableAfterSignalData, "AfterSignalData", id, key, data, length, start_timestamp, period, row_is_del)

不管float data[10];还是std::vector<float> dat 都报错  error C2665: “ormpp::ormpp_sqlite::type_to_name”:

**Comment by Jacyking** [comment]
数据库里没有这个类型…
