### ISSUE TITLE
wsl2-ubuntu22.04.5 上使用apt安装的libmysqlclient 使用ormpp连接mysql失败

### ISSUE THREAD

**Issue by KkemChen** [qicosmos/ormpp#182]
![image](https://github.com/user-attachments/assets/0a93be7e-4a78-4196-811e-c28c4bb992a4)

![image](https://github.com/user-attachments/assets/b5d3e883-9f08-4738-b283-d8aa3ae59b6e)

使用navicat或命令行工具都能成功连接进去

**Comment by Jacyking** [comment]
在终端里连接

**Comment by KkemChen** [comment]
无事发生了，是我代码里 openssl版本冲突了
