### ISSUE TITLE
序列化char[]问题

### ISSUE THREAD

**Issue by Deelyn** [qicosmos/ormpp#19]
struct test_tb {
	int id;
	char name[12];
};
REFLECTION(test_tb, id, name);
dbng< sqlite > sqlite;
TEST_REQUIRE(sqlite.create_datatable<test_tb>());

按照示例中的代码，发生编译错误，经过调试发现是char[]引起的
iguana\iguana\reflection.hpp(376): error C2440: “return”: 无法从“char [12]”转换为“char (&&)[12]”
iguana\iguana\reflection.hpp(377): error C3487: “void”: 所有返回表达式必须推导为相同类型: 以前为“char (&&)[12]”

**Comment by qicosmos** [comment]
我今天或者明天看一下这个问题。

**Comment by qicosmos** [comment]
检查一下是不是iguana是不是最新的，另外再看一下你的编译器版本。
我用vs2017 15.7.1编译代码没有编译错误。

**Comment by Deelyn** [comment]
iguana和ormpp都是最新的。看起来是编译器的问题，我的编译器是vs2017 15.8.7，换到稍早一些的15.7.4编译就没有错误。

在15.8.7，char[]似乎是在else分支发生错误，泛型我也不太懂
    template<size_t I, typename T>
    constexpr decltype(auto) get(T&& t)
    {
        using M = decltype(iguana_reflect_members(std::forward<T>(t)));
		using U = decltype(std::forward<T>(t).*(std::get<I>(M::apply_impl())));
		if constexpr(std::is_array_v<U>) {
			auto s = std::forward<T>(t).*(std::get<I>(M::apply_impl()));
			std::array<char, sizeof(U)> arr;
			memcpy(arr.data(), s, arr.size());
			return arr;
		}
		else
        return std::forward<T>(t).*(std::get<I>(M::apply_impl()));
    }

**Comment by qicosmos** [comment]
我后面升级到最新的编译器之后再看这个问题。

**Comment by qicosmos** [comment]
你试试把T&& t的两个引号去掉看看编译过不

**Comment by Deelyn** [comment]
你试试把T&& t的两个引号去掉看看编译过不 ~~~ 不行。

**Comment by Jacyking** [comment]
请更新最新代码
