### ISSUE TITLE
delete_records<person>() do no work

### ISSUE THREAD

**Issue by torbjo** [qicosmos/ormpp#21]
This example (from `README.md`) do not work: `mysql.delete_records<person>();`. But this does: `mysql.delete_records<person>("id > 0");`.

The check for an empty where-condition is commented out here:: https://github.com/qicosmos/ormpp/blob/master/utility.hpp#L172

If that is because a bug in VS2017, maybe wrap in an `#ifdef _MSC_VER` or something.

**Comment by qicosmos** [comment]
Thanks for your issue, i will check it soon.
