### ISSUE TITLE
sqlite查询异常

### ISSUE THREAD

**Issue by IULOVE** [qicosmos/ormpp#25]
![1](https://user-images.githubusercontent.com/14193276/53295563-35e4f700-3839-11e9-9a94-4714d2d0467a.png)
![12](https://user-images.githubusercontent.com/14193276/53295567-45644000-3839-11e9-904c-bc56121fd88a.png)

就这个简单的查询有时候会出现异常，没有写操作，单线程读的，这个异常出现几率小..

**Comment by qicosmos** [comment]
可以捕获一下异常，写到日志里看看是什么异常。把异常信息再出来我看看。

**Comment by IULOVE** [comment]
好的·只有等下次出现异常才能看到·！
