### ISSUE TITLE
error: ‘INT_MIN’ was not declared

### ISSUE THREAD

**Issue by micfan** [qicosmos/ormpp#29]
> gcc --version                                                                                                                                                                             
gcc (GCC) 8.2.1 20181127
Copyright (C) 2018 Free Software Foundation, Inc.

```
ormpp/sqlite.hpp: In member function ‘constexpr int ormpp::sqlite::insert_impl(bool, const string&, const T&, Args&& ...)’:
ormpp/sqlite.hpp:355:24: error: ‘INT_MIN’ was not declared in this scope
                 return INT_MIN;
                        ^~~~~~~
ormpp/sqlite.hpp:355:24: note: ‘INT_MIN’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
```

**Comment by qicosmos** [comment]
好的，我这几天看一下。

**Comment by micfan** [comment]
这个也许是误报，现在编译通过了。

可能在刚才 #12 缺少 inline 修饰的情况下报出此错的；

但改文件的确没 `#include <climits>`


### UPDATE
不是误报

**Comment by qicosmos** [comment]
加了头文件。

**Comment by micfan** [comment]
Good , fixed in https://github.com/qicosmos/ormpp/commit/63bff7572f07f9edcfb971ef9c089886593058da#diff-187c9e2f2609d5cc4d07287a9e831b3aR6
