### ISSUE TITLE
多次包含出现问题

### ISSUE THREAD

**Issue by leochan1** [qicosmos/ormpp#30]
我定义对数据库操作的两个类，然后同时包含必要hpp文件报错，我知道是重复包含错误，想请问一下这个能不能在源码上解决？😳
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2005	"void __cdecl ormpp::get_sql_conditions(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?get_sql_conditions@ormpp@@YAXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 已经在 ExportBankUser.obj 中定义	DllMysqlOrm	D:\vs2017_workspace\test_2017\DllMysqlOrm\exportFunc.obj	1

**Comment by qicosmos** [comment]
要在函数前面加inline，之前也有提了这个issue，如果着急就先自己加，不着急就等我这几天加。

**Comment by qicosmos** [comment]
已经加了inline，你更新一下代码再试试看行不行。

**Comment by leochan1** [comment]
可以，感谢哈
