### ISSUE TITLE
发现mysql 从数据库拉数据时的bug

### ISSUE THREAD

**Issue by jiayuehua** [qicosmos/ormpp#32]
346 行
后应该将所有字段关联的缓冲区memset 0, 否则下次使用的是A记录遗留的垃圾缓存区，而当读下一记录B同一字段的数据时，对于text类型，如果数据库中是null，也就是没数据，将不会读取，这时B记录中直接使用A字段该记录的值。
比如该字段第一条记录 存的是较长的1111111... 第2条较短的2222.... 第三条为空，结果读到的不是空，而是和第2条一样。
![image](https://user-images.githubusercontent.com/3423893/56455706-6d34d780-6394-11e9-87c3-4e9ce0386222.png)

**Comment by jiayuehua** [comment]
已经提交了一个pull request 针对该问题

**Comment by qicosmos** [comment]
我看了你提交的pr，不能直接调用clear方法吗？

**Comment by jiayuehua** [comment]
clear实现可以只是将vector 内部的size_设为0，而不对缓冲区清零，甚至实现可以clear时自由的shrink_to_fit ，这样甚至导致写越界。
vc2017上release模式的如下程序
#include <iostream>
#include <vector>
int main()
{
  std::vector  v(10,5);
  v.clear();
  std::cout<<v.size();
  std::cout<<v[0]<<std::endl;
}
输出
05

**Comment by Jacyking** [comment]
请更新最新代码
