### ISSUE TITLE
mysql 类型从数据库拉数据时的缓存区的优化

### ISSUE THREAD

**Issue by jiayuehua** [qicosmos/ormpp#34]
我认为对于char_array类型，应该将缓冲区直接指向该字段的地址，这样能减少一次拷贝 应当使用如下语句
			param_binds[Idx].buffer = (t.*item);

**Comment by jiayuehua** [comment]
需要记录全读完到vector后，再对vector中的记录类型的所有string字段调用shrink_to_fit.

**Comment by qicosmos** [comment]
我后面再看一下这里能否优化。

**Comment by Jacyking** [comment]
请更新最新代码
