### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by bizehao** [qicosmos/ormpp#36]
因为项目需求的需要，我在尝试添加对mysql8.0的支持，因为大佬引入的是mysql的c api，所以我尝试改为c++的api，遇到了一个问题，你的type_mapping.hpp里的那些函数返回的都是字符串后面有一个sv，想问一下这个sv是什么？我没找到在哪块定义的

**Comment by qicosmos** [comment]
这个是c++17 std::string_view里面的

**Comment by bizehao** [comment]
明白了 谢谢
