### ISSUE TITLE
能否只安装和编译部分数据库的支持？

### ISSUE THREAD

**Issue by RubikZero** [qicosmos/ormpp#39]
例如我只需要使用sqlite，在不安装mysql，postgresql的情况下也可编译此项目

**Comment by qicosmos** [comment]
可以的，有三个编译选项用来控制是否启用某个数据库。
ENABLE_MYSQL 
ENABLE_SQLITE3 
ENABLE_PG 

比如你只想用sqlite就启用ENABLE_SQLITE3编译选项。

**Comment by qicosmos** [comment]
已经解决。
