### ISSUE TITLE
Mysql接口 查询指定数据失败

### ISSUE THREAD

**Issue by zhenghl1** [qicosmos/ormpp#42]
我使用MySQL+Vs2019 测试 main.cpp 中的代码，发现TEST_CASE(orm_query) 部分 查找指定 “id=1” 失败，生成的 SQL 语句不含 “where”。 请确认

**Comment by qicosmos** [comment]
我看一下。

**Comment by qicosmos** [comment]
确认了，这样写的时候，需要自己加上where字符串。后续会优化掉。现在这种需要写很多sql脚本的方式不太好，后续回提供一些stream api，让使用更安全友好。
