### ISSUE TITLE
如何配置mysql的连接端口

### ISSUE THREAD

**Issue by wngmng** [qicosmos/ormpp#43]
默认的连接方式不能指定端口，connect默认使用3306端口。
我在用mysql.connect(ip, mysql_name, mysql_password, mysql_db, port_);进行连接时发现port_这个参数起不到作用，请问如果端口不是3306时我在哪里指定呢？

**Comment by qicosmos** [comment]
之前写的时候把端口写死成默认端口了，这里需要完善一下。

**Comment by wngmng** [comment]
好的，谢谢回答

**Comment by paxifaer** [comment]
请问这个问题解决了吗

**Comment by paxifaer** [comment]
找到了，我的版本太老了
