### ISSUE TITLE
编译成LIB文件后，我该如何使用，还未深入学习库

### ISSUE THREAD

**Issue by uestc-alayi** [qicosmos/ormpp#46]
因课设需求，需要用到您的库，在编译成LIB文件后，我需要在工程中加入lib（main.lib）和哪些头文件

**Comment by qicosmos** [comment]
有example，你把example运行起来，用sqlite的话最简单，依赖sqlite的头文件和lib

**Comment by Jacyking** [comment]
请更新最新代码
