### ISSUE TITLE
utility.cpp 111行

### ISSUE THREAD

**Issue by huangjun0210** [qicosmos/ormpp#49]
`
#ifdef ORMPP_ENABLE_PG
        std::string quota_name = "'" + std::string(iguana::get_name<T>()) + "'";
#else
`
应该将单引号去掉，不然报错
`
#ifdef ORMPP_ENABLE_PG
        std::string quota_name = std::string(iguana::get_name<T>()) ;
#else
`

**Comment by qicosmos** [comment]
hi，你可以提一个pr吗？

**Comment by Jacyking** [comment]
已修复
