### ISSUE TITLE
在Mac上报错，std::string不能在constexpr环境中

### ISSUE THREAD

**Issue by Kidsunbo** [qicosmos/ormpp#52]
编译器：
Apple clang version 11.0.3 (clang-1103.0.32.62)

报错：
Variable of non-literal type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') cannot be defined in a constexpr function。

基本上都是这个错误，很多。想问一下是不是编译器不支持？

**Comment by qicosmos** [comment]
需要去掉constexpr，可以提一个pr。

**Comment by Kidsunbo** [comment]
已提
