### ISSUE TITLE
请问如何创建主键类型为string类型的表

### ISSUE THREAD

**Issue by daitouguan** [qicosmos/ormpp#53]
比如我的表结构是
struct student
{
string name；
int age；
}
name为表的主键，该如何创建呢。
我按照你的例子创建出来错误提示是：BLOB/TEXT column 'name' used in key specification without a key length

**Comment by qicosmos** [comment]
现在主键不支持字符串。一般也不会把字符串作为主键的。

**Comment by wahello** [comment]
其实，现在用字符串做主键很普遍。比如uuid，ulid, SnowFlake 的主键都很常见。

**Comment by Jacyking** [comment]
已支持
