### ISSUE TITLE
关于使用mysql的版本

### ISSUE THREAD

**Issue by chenhao86** [qicosmos/ormpp#55]
使用mysql是什么版本的，这边没找到mysql8.0+ 的C的头文件。 用的5.0的版本 +VS2019 ，编译报错。

**Comment by qicosmos** [comment]
好像是5.7的connector库，7点几的也有。

**Comment by chenhao86** [comment]
哦，好的。我这边再试试看。

**Comment by chenhao86** [comment]
奇怪了。还是报错。感觉 象是mysql 的lib版本过低，或vs版本过高导致的。
1>------ 已启动生成: 项目: ormpp, 配置: Debug Win32 ------
1>mysqlclient.lib(plugin_client.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(plugin_client.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(client_authentication.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(client_authentication.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(my_default.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(my_default.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(ssl.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(ssl.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(net_serv.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(net_serv.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(handshake_client.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(handshake_client.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(yassl_int.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(yassl_int.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(my_aes_yassl.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(my_aes_yassl.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(crypto_wrapper.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(crypto_wrapper.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(yassl_imp.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(yassl_imp.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(handshake.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(handshake.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(cert_wrapper.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(cert_wrapper.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(asn.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(asn.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(my_rnd.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(my_rnd.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(crypt_genhash_impl.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(crypt_genhash_impl.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(my_sha1.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(my_sha1.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(handshake.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(handshake.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(common.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(common.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(log_client.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(log_client.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(integer.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(integer.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(my_aes.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(my_aes.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(dsa.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(dsa.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(dh.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(dh.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(rsa.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(rsa.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>mysqlclient.lib(algebra.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项: 值“1600”不匹配值“1900”(main.obj 中)
1>mysqlclient.lib(algebra.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(main.obj 中)
1>LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
1>mysqlclient.lib(log_client.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(my_init.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(my_thr_init.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(my_mess.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(my_winfile.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(client.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(my_default.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(typelib.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(viosslfactories.obj) : error LNK2001: 无法解析的外部符号 ___iob_func
1>mysqlclient.lib(ctype.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(xml.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(client.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(libmysql.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(password.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(my_time.obj) : error LNK2001: 无法解析的外部符号 _sprintf
1>mysqlclient.lib(client.obj) : error LNK2019: 无法解析的外部符号 __snprintf，该符号在函数 _set_connect_attributes 中被引用
1>mysqlclient.lib(ssl.obj) : error LNK2001: 无法解析的外部符号 __snprintf
1>mysqlclient.lib(crypt_genhash_impl.obj) : error LNK2001: 无法解析的外部符号 __snprintf
1>mysqlclient.lib(my_default.obj) : error LNK2019: 无法解析的外部符号 _printf，该符号在函数 _my_load_defaults 中被引用
1>mysqlclient.lib(log_client.obj) : error LNK2019: 无法解析的外部符号 _vfprintf，该符号在函数 "void __cdecl error_log_vprint(enum error_log_level::type,char const *,char *)" (?error_log_vprint@@YAXW4type@error_log_level@@PBDPAD@Z) 中被引用
1>E:\Projects\github\ormpp_mysql\Debug\ormpp.exe : fatal error LNK1120: 5 个无法解析的外部命令
1>已完成生成项目“ormpp.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========

**Comment by Jacyking** [comment]
8.0也支持的
