### ISSUE TITLE
Deleting a single row

### ISSUE THREAD

**Issue by opakaj** [qicosmos/ormpp#56]
Deleting a single row doesn't work.
Please show how.
It says there isn't an overridden function  for that.

**Comment by qicosmos** [comment]
Please provide the test code.

**Comment by opakaj** [comment]
![ormpp](https://user-images.githubusercontent.com/78092188/106185579-0de43800-61b4-11eb-8164-49c8c7d2f973.png)

It says no instance of the overloaded function "ormpp::dbng<DB>::delete_records  for;

Mysql.delete_records<person>("id=1");
Mysql.delete_records<person>(" ");

**Comment by opakaj** [comment]
??

**Comment by Jacyking** [comment]
Please git pull the laster code
