### ISSUE TITLE
只支持c++17要求太高了，会考虑出c++11的版本吗

### ISSUE THREAD

**Issue by datonli** [qicosmos/ormpp#7]

**Comment by qicosmos** [comment]
即使支持了c++11，又有人要求支持c++14，其实就是升级编译器的事儿，不是多难的事儿啊。
如果你用ubuntu18.04，直接就gcc7.3自动支持c++17了。或者自己升级一下gcc了。
win上就下载最新的vs2017就行了，不麻烦啊。

其实支持c++11也好c++14也好，都不是太大的问题，关键是时间，没有那么多业余时间去做，现在手头不少开源项目等着完善呢。

**Comment by prettybxp** [comment]
嵌入式设备的编译器不是想升级就升级的，比如海思交叉编译版本比较低

**Comment by prettybxp** [comment]
> 即使支持了c++11，又有人要求支持c++14，其实就是升级编译器的事儿，不是多难的事儿啊。
> 如果你用ubuntu18.04，直接就gcc7.3自动支持c++17了。或者自己升级一下gcc了。
> win上就下载最新的vs2017就行了，不麻烦啊。
> 
> 其实支持c++11也好c++14也好，都不是太大的问题，关键是时间，没有那么多业余时间去做，现在手头不少开源项目等着完善呢。

嵌入式设备的编译器不是想升级就升级的，比如海思交叉编译版本比较低

**Comment by qicosmos** [comment]
哎，现在工作挺忙的，没有时间去做这个事，只能等以后有时间了再搞了。
