### ISSUE TITLE
FID(student::code, "=", 5) error

### ISSUE THREAD

**Issue by lemon19900815** [qicosmos/ormpp#74]
1、使用FID查询不能获取到正确的结果，我查阅了其他issue，有一条可能是你优化query<student>("")结果,在序列化generate_query_sql中去掉了where_sql的赋值操作，导致通过FID查询序列化时最终的sql没有where关键字而导致查询失败；
2、我可以通过修改generate_query_sql中关于where_sql的赋值来解决这个问题，但通过`query<student>("where code = 5")`这种方式就需要同时调整为`query<student>("code = 5")`去掉**where**关键字。而且这样做之后，对上面我提到的那个issue的修改就会失效，即`query<student>("")`拿不到结果；

**Comment by qicosmos** [comment]
where应该去掉的哈，你可以适配一下，或者我晚点改一下。
