### ISSUE TITLE
varchar(255)  字段

### ISSUE THREAD

**Issue by life2122** [qicosmos/ormpp#75]
如题，create_datatable 如何实现j建表到mysql数据库是varchar(255) 类型，而不是TEXT类型

**Comment by qicosmos** [comment]
现在还没支持，可以先通过脚本创建表绕过一下。

**Comment by qicosmos** [comment]
一直想重构一下，把功能搞得更完整一点，等晚点发起重构的共建吧，希望有更多人参与进来。

**Comment by life2122** [comment]
实属新手，看了下代码，建表可以std::array<char,N>,  但是其它的SQL就无法执行了，能力有限
