### ISSUE TITLE
添加编译选项

### ISSUE THREAD

**Issue by Jackson-soft** [qicosmos/ormpp#8]
在作为ORM库用的时候，我们一般只需要某一个数据库，而此库的编译是需要三个后端数据的头文件，我觉得这有点不妥？
能不能增加编译选项来编译指定的数据库？

**Comment by qicosmos** [comment]
这个事在计划当中，接下来我会做这个事。

**Comment by qicosmos** [comment]
@Jackson-soft 已经增加了编译选项，现在默认是mysql数据库，如果要支持其它两个库自己打开编译开关即可。

**Comment by Jackson-soft** [comment]
赞！
