### ISSUE TITLE
请问一条数据里,某些字段如何设置为NULL呢?

### ISSUE THREAD

**Issue by HorrZzz** [qicosmos/ormpp#92]
例如这样:
![image](https://user-images.githubusercontent.com/42233737/233884882-c3efe0eb-ee45-4c5f-ac86-ccb8af8cda9c.png)

**Comment by Jacyking** [comment]
sqlite已支持 需要使用optional，[代码示例](https://github.com/qicosmos/ormpp/blob/master/example/main.cpp)

**Comment by HorrZzz** [comment]
> sqlite已支持 需要使用optional，[代码示例](https://github.com/qicosmos/ormpp/blob/master/example/main.cpp)

感谢,请问MySQL现在是不是还不支持设置为NULL呀?

**Comment by Jacyking** [comment]
是的 稍后会支持
