### ISSUE TITLE
mysql的query函数无法正确获得NULL字段的内容

### ISSUE THREAD

**Issue by Eggache666** [qicosmos/ormpp#99]
表结构：
struct person
{
	int id;
	std::string name;
	int age;
};
REFLECTION(person, id, name, age)

有如下内容
| id | name | age |
|---|------|-------|
|  0 | hehe  | 100 |
|  1 | NULL | 100 |
|  2 | NULL | 100 |
|  4 | NULL | 100 |
|  5 | haha  | 100 |
------------------

当按如下方式查询时
auto result = mysql.query<person>("select * from person");
得到的result结果为：
| id | name | age |
|----|-----|-------|
|  0 | hehe  | 100 |
|  1 | hehe  | 100 |
|  2 | hehe  | 100 |
|  4 | hehe  | 100 |
|  5 | haha  | 100 |
-------------------

自己尝试在mysql.hpp 340行下添加：
for (auto &item : mp)
        item[0] = '\0';
两句后，能得到正常的结果，不知此方法是否正确。

麻烦请帮忙消除上述bug

**Comment by Jacyking** [comment]
![QXCLSZHJH@U`D2K_M`{BE8P](https://github.com/qicosmos/ormpp/assets/43704572/8dfe169b-d7b6-4e0a-97cf-f6c1547a0285)
![K4L8WC TCF)61YEO79N 0L0](https://github.com/qicosmos/ormpp/assets/43704572/c695665d-5ef4-4a2e-825a-a53e42181034)
暂未发现此问题

**Comment by Jacyking** [comment]
更新最新代码即可
